name: Deploy to Railway Production

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install TypeScript
        run: npm i -g typescript

      - name: Install Packages
        run: npm install

      - name: Install Railway CLI
        run: npm i -g @railway/cli

      - name: Build TypeScript
        run: tsc

      - name: Deploy to Railway
        run: railway up --service ${{ secrets.PROD_RAILWAY_SERVICE_ID }}
        env:
          RAILWAY_TOKEN: ${{ secrets.PROD_RAILWAY_TOKEN }}